### ISSUE TITLE
Cannot have it working for Windows 7. Is that possbile?

### ISSUE THREAD

**Issue by atmavan** [derkalle4/python3-idotmatrix-client#23]
Cannot have it working for Windows 7. Is that possbile?

**Comment by atmavan** [comment]
where to get device bluetooth address?

**Comment by derkalle4** [comment]
Hi @atmavan,

this tool is not finished yet, therefore I do not have time to provide any kind of documentation for Windows. Would be useless anyway, because things will change.

It should work on Windows, though. At least somebody tested it on Windows 11, see #22 

Getting the bluetooth address currently requires a little bit of python code on your own until we have finished an implementation, see #17 

Resolving your issue. Windows is not a priority before we have finished reverse-engineering and improved code quality.

Kind Regards,
Kalle

**Comment by schorsch3000** [comment]
Another way to find the bluetooth-address ist just using bluetooth discovery with any bluetooth enabled device.
Just powerup the display and do not connect to it.
Than open the ui element to find new bluetooth devices and search for the item starting with IDM-
